name: "daily-dev-devcard"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *' # Runs Every 3 Hours

jobs:
  update_devcard:
    name: "daily-dev-devcard"
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.4
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: AnishDe12020/AnishDe12020
          event-type: hashnode-blogs

