name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "anishde12020/action-hashnode-blog@fix-dateUpdated"
        with:
          USERNAME: 'AnishDe12020' # Hashnode Username
          COUNT: 10 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://blog.anishde.dev/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
