name: "hashnode-blogs"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [hashnode-blogs]

jobs:
  update_blogs:
    name: "hashnode-blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "anishde12020/action-hashnode-blog@remove-edited-if-doesnt-exist"
        with:
          USERNAME: 'AnishDe12020' # Hashnode Username
          COUNT: 3 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://blog.anishde.dev/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: AnishDe12020/AnishDe12020
          event-type: metrics
