name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: Base Metrics
        uses: anishde12020/metrics@master
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_stars: yes
          plugin_lines: yes
          plugin_stargazers: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_SECRET }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
      
          
      - name: Achievements
        uses: anishde12020/metrics@master
        with:
          filename: metrics.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact 
          
      - name: Tweets
        uses: anishde12020/metrics@master
        with:
          filename: metrics.tweets.svg
          token: NOT_NEEDED
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_limit: 5
      
      # - uses: anishde12020/metrics@master
      #   with:
      #     # Your GitHub token
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     plugin_isocalendar: yes
      #     plugin_languages: yes
      #     plugin_languages_details: lines, percentage
      #     plugin_languages_sections: most-used, recently-used
      #     plugin_habits: yes
      #     plugin_habits_charts: yes
      #     plugin_stars: yes
      #     plugin_lines: yes
      #     plugin_stargazers: yes
      #     plugin_achievements: yes
      #     plugin_achievements_display: compact 
      #     plugin_notable: yes
      #     plugin_notable_repositories: yes
      #     plugin_tweets: yes
      #     plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
      #     plugin_tweets_limit: 5
      #     plugin_wakatime: yes
      #     plugin_wakatime_token: ${{ secrets.WAKATIME_SECRET }}
      #     plugin_wakatime_sections: time, languages, languages-graphs, editors, os
