name: Metrics
on:
  # Schedule updates (every 3 hours)
  schedule: [{cron: "0 */3 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: Top Left Metrics
        uses: anishde12020/metrics@master
        with:
          filename: metrics.top.left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used
          config_order: base.header, introduction, base.activity+community, base.repositories, isocalendar, languages
      
      - name: Top Right Metrics
        uses: anishde12020/metrics@master
        with:
          filename: metrics.top.right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_SECRET }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          config_order: notable, wakatime 
          
      - name: Bottom Left Metrics
        uses: anishde12020/metrics@master
        with:
          filename: metrics.bottom.left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact 
          plugin_habits: yes
          plugin_habits_charts: yes
          config_order: achievements, habits
          
      - name: Bottom Right Metrics
        uses: anishde12020/metrics@master
        with:
          filename: metrics.bottom.right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_limit: 3
          plugin_stargazers: yes
          plugin_lines: yes
          plugin_stars: yes
          config_order: lines, stars, stargazers, tweets
      
      # - uses: anishde12020/metrics@master
      #   with:
      #     # Your GitHub token
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     plugin_isocalendar: yes
      #     plugin_languages: yes
      #     plugin_languages_details: lines, percentage
      #     plugin_languages_sections: most-used, recently-used
      #     plugin_habits: yes
      #     plugin_habits_charts: yes
      #     plugin_stars: yes
      #     plugin_lines: yes
      #     plugin_stargazers: yes
      #     plugin_achievements: yes
      #     plugin_achievements_display: compact 
      #     plugin_notable: yes
      #     plugin_notable_repositories: yes
      #     plugin_tweets: yes
      #     plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
      #     plugin_tweets_limit: 5
      #     plugin_wakatime: yes
      #     plugin_wakatime_token: ${{ secrets.WAKATIME_SECRET }}
      #     plugin_wakatime_sections: time, languages, languages-graphs, editors, os
