name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: anishde12020/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_stars: yes
          plugin_lines: yes
          plugin_stargazers: yes
          plugin_projects: yes
          plugin_achievements: yes
          plugin_achievements_display: compact 
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_limit: 5
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_SECRET }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
